#!/bin/bash
#
# Copyright 2018 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

. "${BASH_SOURCE%/*}/common.sh"

IMAGE_PATH=$(get_image_path)
[[ -n "$IMAGE_PATH" ]] || die "failed to determine image path"

set -o pipefail

function usage() {
	echo "$(basename "$0"): $*" >&2
	echo "Usage: $(basename "$0") <version>"
	exit 2
}

function apt_get() {
	DEBIAN_FRONTEND=noninteractive apt-get \
		-o Dpkg::Options::="--force-confdef" \
		-o Dpkg::Options::="--force-confold" \
		"$@"
}

while getopts ':rlBfs' c; do
	case $c in
	r | l | B | f | s) ;; # LX-72: For now, silently ignore these.
	*) usage "illegal options -- $OPTARG" ;;
	esac
done

#
# It's possible for delphix-entire not to be already installed on the
# root filesystem being upgraded when we're doing a not-in-place upgrade.
# Thus, when we can't determine the installed version of delphix-entire,
# we assume we're doing a not-in-place upgrade, and skip this check.
#
INSTALLED_VERSION=$(get_installed_version)
[[ -n "$INSTALLED_VERSION" ]] && verify_upgrade_is_allowed

if [[ -f /etc/apt/sources.list ]]; then
	mv /etc/apt/sources.list /etc/apt/sources.list.orig ||
		die "failed to save /etc/apt/sources.list"
fi

cat <<EOF >/etc/apt/sources.list ||
deb [trusted=yes] file://$IMAGE_PATH/public bionic delphix
EOF
	die "failed to configure apt sources"

apt_get update || die "failed to update apt sources"

source_version_information
apt_get install -y "delphix-entire=$VERSION" ||
	die "upgrade failed; from '$INSTALLED_VERSION' to '$VERSION'"

if [[ -f /etc/apt/sources.list.orig ]]; then
	mv /etc/apt/sources.list.orig /etc/apt/sources.list ||
		die "failed to restore /etc/apt/sources.list"
fi

exit 0
