#!/bin/bash
#
# Copyright 2018 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

. "${BASH_SOURCE%/*}/common.sh"

set -o pipefail

function usage() {
	echo "$(basename "$0"): $*" >&2
	echo "Usage: $(basename "$0") <version>"
	exit 2
}

function apt_get() {
	DEBIAN_FRONTEND=noninteractive apt-get \
		-o Dpkg::Options::="--force-confdef" \
		-o Dpkg::Options::="--force-confold" \
		"$@"
}

function pkg_version_impl() {
	apt-cache policy "$1" | grep "$2" | awk '{print $2}'
}

function pkg_version_installed() {
	pkg_version_impl "$1" "Installed:"
}

function pkg_version_candidate() {
	pkg_version_impl "$1" "Candidate:"
}

while getopts ':' c; do
	case $c in
	r | l | B | f | s) ;; # LX-72: For now, silently ignore these.
	*) usage "illegal options -- $OPTARG" ;;
	esac
done

[[ $# -eq 1 ]] || die "Must specify a target verison."
DLPX_VERSION="$1"

[[ -d "$UPDATE_DIR" ]] || die "update directory '$UPDATE_DIR' does not exist"
[[ -d "$UPDATE_DIR/$1" ]] ||
	die "upgrade image for version '$DLPX_VERSION' was not unpacked"

cat <<EOF >/etc/apt/sources.list ||
	deb [trusted=yes] file://$UPDATE_DIR/$DLPX_VERSION/public bionic delphix
EOF
	die "failed to configure apt sources"

apt_get update || die "failed to update apt sources"

INSTALLED_VERSION=$(pkg_version_installed "delphix-entire")
CANDIDATE_VERSION=$(pkg_version_candidate "delphix-entire")

apt_get install -y "delphix-entire=$CANDIDATE_VERSION" ||
	die "upgrade failed; from '$INSTALLED_VERSION' to '$CANDIDATE_VERSION'"

exit 0
