#
# Copyright (c) 2019, 2025 by Delphix. All rights reserved.
#
# Configuration drop-in for a dcenter.
#
# The default setting for the number of nfs threads is too low. To
# improve performance we reset the value to 64 which mimics what
# we use on the delphix engine.
#
#
[nfsd]
threads=64

[mountd]
threads=5
manage-gids=y
