#!/bin/bash
#
# Copyright 2018 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# [WIP]
# The existence of this file is checked by dx_unpack, thus we provide
# it as an empty file until the needed functionality is added.
#

function report_progress_inc() {
	echo "Progress increment: $(date +%T:%N%z), $1, $2"
}

report_progress_inc 100

exit 0
