#
# Copyright 2018,2020 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
- name: Clone the dcenter-gate repo
  ansible.builtin.git:
    repo: "https://{{ lookup('env', 'GITHUB_TOKEN') }}@github.com/delphix/dcenter-gate.git"
    version: main
    dest: /opt/dcenter/lib/dcenter-gate
    accept_hostkey: true
    update: false
  when: lookup('env', 'GITHUB_TOKEN') != ''

- name: Set java to java-8-openjdk-amd64
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/bin/java

#
# By default, ubuntu restricts directories where dhcpd and named
# can operate. For dcenter, we maintain the dhcp configuration
# in /tmp so we need to add those paths into the apparmor configuration.
#
- name: Create the apparmor configuration for dhcpd
  ansible.builtin.copy:
    dest: "/etc/apparmor.d/local/usr.sbin.dhcpd"
    content: |
      /tmp/dcenter_dhcp_config/ r,
      /tmp/dcenter_dhcp_config/** r,
      /tmp/dcenter_dhcp_config/dhcpd{,6}.conf r,
      /tmp/dcenter_dhcp_config/dhcpd{,6}_ldap.conf r,
      /tmp/dcenter_dhcp_config/dhcpd{,6}.leases* lrw,
      /tmp/dcenter_dhcp_config/dhcpd{,6}.pid rw,
    mode: "0644"

- name: Create the apparmor configuration for named
  ansible.builtin.copy:
    dest: "/etc/apparmor.d/local/usr.sbin.named"
    content: |
      /tmp/dcenter_dhcp_config/named.conf r,
      /tmp/dcenter_dhcp_config/named.zone r,
      /tmp/dcenter_dhcp_config/named.pid w,
    mode: "0644"

<<<<<<< Updated upstream
#
# The default setting for the number of nfs threads is too low. To
# improve performance we reset the value to 64 which mimics what
# we use on the delphix engine.
#
- name: Update nfs.conf | Update the number of nfsd threads
  community.general.ini_file:
    path: /etc/nfs.conf
    section: nfsd
    option: threads
    value: 64

- name: Update nfs.conf | Update the number of mountd threads
  community.general.ini_file:
    path: /etc/nfs.conf
    section: mountd
    option: threads
    value: 5

- name: Update nfs.conf | Set manage-gids to yes
  community.general.ini_file:
    path: /etc/nfs.conf
    section: mountd
    option: manage-gids
    value: yes # noqa yaml[truthy]


- name: Add dcenter-specific NFS overrides to /etc/nfs.conf.d/12-delphix-dcenter-nfs-overrides.conf
  copy:
    src: etc/
    dest: /etc/
    owner: root
    group: root
    mode: 0444

- name: Mask named and dhcp services
  ansible.builtin.systemd_service:
    name: named.service
    masked: true

- name: Mask named and dhcp services
  ansible.builtin.systemd_service:
    name: isc-dhcp-server.service
    masked: true

- name: Mask named and dhcp services
  ansible.builtin.systemd_service:
    name: isc-dhcp-server6.service
    masked: true

#
# delphix-platform installs ntp in a disabled state by default.
# We want to enable ntp to keep the time in sync on DCenter as clock skew
# can cause operational problems.
#
# For example, we run awscli on DCenter hosts, and some preliminary searching
# shows that aws s3 commands can return RequestTimeTooSkewed errors if there
# is clock skew.
#
# We also have cleanup jobs that run on DCenter hosts that rely on filesystem
# timestamps being accurate.
#
- name: Enable NTP systemd service
  ansible.builtin.systemd_service:
    name: ntp.service
    enabled: true
