#!/bin/bash
#
# Copyright 2018, 2025 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

. "${BASH_SOURCE%/*}/common.sh"

IMAGE_PATH=$(get_image_path)
[[ -n "$IMAGE_PATH" ]] || die "failed to determine image path"

CONTAINER=

TMP_DATASETS_EXIST=false

# Verify whether both /tmp and /var/tmp ZFS datasets exist for the specified container.
# If both datasets are present, the system is considered CIS compliant.
# In such cases, handle the /tmp and /var/tmp mounts appropriately during the upgrade process.
# To ensure this handling, set the TMP_DATASETS_EXIST variable to true.
if zfs list "rpool/ROOT/$CONTAINER/tmp" >/dev/null 2>&1 && zfs list "rpool/ROOT/$CONTAINER/vartmp" >/dev/null 2>&1; then
	TMP_DATASETS_EXIST=true
fi

function create_cleanup() {
	#
	# Upon successful creation of the container, don't perform any
	# cleanup logic. Rather, the consumer of the script should
	# eventually "destroy" the container.
	#
	# shellcheck disable=SC2181
	[[ "$?" -eq 0 ]] && return

	#
	# If the CONTAINER variable is empty, this means the create
	# function failed before the container directory could be
	# created. Thus, there's nothing to clean up, so we can
	# immediately exit.
	#
	[[ -z "$CONTAINER" ]] && return

	destroy "$CONTAINER"
}

function create_upgrade_container() {
	trap create_cleanup EXIT
	local type="$1"

	case "$type" in
	in-place | not-in-place | rollback) ;;

	*)
		die "unsupported upgrade container type specified: '$1'"
		;;
	esac

	#
	# We want to use "/var/lib/machines" as the parent directory,
	# since that directory is used by "systemd-nspawn" when looking
	# for containers.  This way, we can create the directory and
	# mount our rootfs clone here, and "systemd-nspawn" will
	# automatically detect it.
	#
	DIRECTORY=$(mktemp -d -p "/var/lib/machines" -t delphix.XXXXXXX)
	[[ -d "$DIRECTORY" ]] || die "failed to create upgrade directory"
	CONTAINER=$(basename "$DIRECTORY")
	[[ -n "$CONTAINER" ]] || die "failed to obtain upgrade name"

	ROOTFS_DATASET=$(get_mounted_rootfs_container_dataset)
	[[ -n "$ROOTFS_DATASET" ]] ||
		die "unable to determine mounted rootfs container dataset"

	#
	# We'll set the version property differently based on the
	# upgrade container that we're created (e.g. in-place vs.
	# not-in-place vs. rollback). Thus, we explicity don't set any
	# version property here, and instead defer setting that property
	# until later, in upgrade container type specific code.
	#
	zfs create \
		-o canmount=off \
		-o mountpoint=none \
		"rpool/ROOT/$CONTAINER" ||
		die "failed to create upgrade filesystem"

	case "$type" in
	in-place | not-in-place)
		#
		# When creating a new "in-place" or "not-in-place"
		# upgrade container, we need to snapshot the currently
		# mounted rootfs datasets, so these snapshots can be
		# used to create the new container datasets below.
		#
		SNAPSHOT_NAME="container-$CONTAINER"
		zfs snapshot -r "$ROOTFS_DATASET@$SNAPSHOT_NAME" ||
			die "failed to create upgrade container snapshots"

		#
		# The properties for a snapshot will inherit its values
		# from the parent dataset by default. Thus, in order for
		# this property to reflect the version contained in this
		# specific snapshot, we need to explicity set the
		# property here.
		#
		copy_required_dataset_property "$PROP_CURRENT_VERSION" \
			"$ROOTFS_DATASET" "$ROOTFS_DATASET@$SNAPSHOT_NAME"
		copy_optional_dataset_property "$PROP_HOTFIX_VERSION" \
			"$ROOTFS_DATASET" "$ROOTFS_DATASET@$SNAPSHOT_NAME"
		#
		# The minimum version property was introduced in 6.0.12.0.
		#
		if compare_versions "$(get_current_version)" ge "6.0.12.0"; then
			copy_required_dataset_property "$PROP_MINIMUM_VERSION" \
				"$ROOTFS_DATASET" "$ROOTFS_DATASET@$SNAPSHOT_NAME"
		fi
		;;
	rollback)
		#
		# When the "execute" script is used to perform an
		# in-place upgrade, it will create a snapshot on the
		# rootfs container datasets that are upgraded. It's this
		# snapshot name that we're attempting to find here, as
		# these snapshots are used to create the new "rollback"
		# upgrade container datasets below.
		#
		SNAPSHOT_NAME=$(get_dataset_rollback_snapshot_name "$ROOTFS_DATASET")
		[[ -n "$SNAPSHOT_NAME" ]] ||
			die "unable to determine rollback snapshot name"
		;;
	esac

	case "$type" in
	in-place | not-in-place | rollback)
		#
		# For in-place and rollback containers, we create the
		# root filesystem by cloning an existing container.
		# Thus, for these, we want the new container's version
		# properties to match the dataset being cloned.
		#
		copy_required_dataset_property "$PROP_INITIAL_VERSION" \
			"$ROOTFS_DATASET@$SNAPSHOT_NAME" "rpool/ROOT/$CONTAINER"
		copy_required_dataset_property "$PROP_CURRENT_VERSION" \
			"$ROOTFS_DATASET@$SNAPSHOT_NAME" "rpool/ROOT/$CONTAINER"
		copy_optional_dataset_property "$PROP_HOTFIX_VERSION" \
			"$ROOTFS_DATASET@$SNAPSHOT_NAME" "rpool/ROOT/$CONTAINER"
		#
		# The minimum version property was introduced in 6.0.12.0.
		#
		if compare_versions "$(get_current_version)" ge "6.0.12.0"; then
			copy_required_dataset_property "$PROP_MINIMUM_VERSION" \
				"$ROOTFS_DATASET@$SNAPSHOT_NAME" "rpool/ROOT/$CONTAINER"
		fi

		zfs clone \
			-o canmount=noauto \
			-o mountpoint="$DIRECTORY" \
			"$ROOTFS_DATASET/root@$SNAPSHOT_NAME" \
			"rpool/ROOT/$CONTAINER/root" ||
			die "failed to create upgrade / clone"

		zfs mount "rpool/ROOT/$CONTAINER/root" ||
			die "failed to mount upgrade / clone"
		;;
	esac

	zfs clone \
		-o mountpoint=legacy \
		"$ROOTFS_DATASET/home@$SNAPSHOT_NAME" \
		"rpool/ROOT/$CONTAINER/home" ||
		die "failed to create upgrade /home clone"

	zfs clone \
		-o mountpoint=legacy \
		"$ROOTFS_DATASET/data@$SNAPSHOT_NAME" \
		"rpool/ROOT/$CONTAINER/data" ||
		die "failed to create upgrade /var/delphix clone"

	zfs clone \
		-o mountpoint=legacy \
		"$ROOTFS_DATASET/log@$SNAPSHOT_NAME" \
		"rpool/ROOT/$CONTAINER/log" ||
		die "failed to create upgrade /var/log clone"

	if $TMP_DATASETS_EXIST; then
		zfs clone \
			-o mountpoint=legacy \
			"$ROOTFS_DATASET/tmp@$SNAPSHOT_NAME" \
			"rpool/ROOT/$CONTAINER/tmp" ||
			die "failed to create upgrade /tmp clone"

		zfs clone \
			-o mountpoint=legacy \
			"$ROOTFS_DATASET/vartmp@$SNAPSHOT_NAME" \
			"rpool/ROOT/$CONTAINER/vartmp" ||
			die "failed to create upgrade /var/tmp clone"
	fi

	case "$type" in
	not-in-place)
		#
		# We need to ensure all of the upgrade container's datasets
		# are mounted before running "debootstrap". This way, if any
		# packages installed by "debootstrap" happen to deliver
		# files to any of these directories, they'll be propertly
		# delivered to the correct dataset, rather than the root
		# dataset.
		#
		mount_upgrade_container_dataset \
			"rpool/ROOT/$CONTAINER/home" "$DIRECTORY/home"
		mount_upgrade_container_dataset \
			"rpool/ROOT/$CONTAINER/data" "$DIRECTORY/var/delphix"
		mount_upgrade_container_dataset \
			"rpool/ROOT/$CONTAINER/log" "$DIRECTORY/var/log"

		if $TMP_DATASETS_EXIST; then
			mount_upgrade_container_dataset \
				"rpool/ROOT/$CONTAINER/tmp" "$DIRECTORY/tmp"
			mount_upgrade_container_dataset \
				"rpool/ROOT/$CONTAINER/vartmp" "$DIRECTORY/var/tmp"
		fi

		#
		# This function needs to return the container's name to
		# stdout, so that consumers of this function/script can
		# consume that name and then later start/stop/destroy the
		# container. Thus, we have to redirect the output from
		# debootstrap away from stdout.
		#
		# Also, we need to include the "systemd-container" package
		# when installing the base systemd with debootstrap so that
		# starting the container will work properly. Otherwise,
		# after starting the container, we won't be able to
		# communicate and later run commands in the container with
		# "systemd-run".
		#
		# On Ubuntu 20.04, in-order to satisfy some package
		# dependencies, we must set the variant to "minbase" and list
		# "ntp" in the include list before "systemd-container".
		# Setting the variant to minbase removes systemd from the
		# packages being installed by default. Systemd will still
		# be installed, but in a later pass, as a dependency of
		# systemd-container. The reason we need to go through those
		# hoops is the following:
		#  - systemd has a package dependency on a "time-daemon"
		#    virtual package, which is provided by either "ntp" or
		#    "systemd-timesyncd".
		#  - If a time-deamon is not already installed when
		#    installing systemd, then systemd will try to
		#    install systemd-timesyncd.
		#  - systemd-timesyncd is not available in our upgrade
		#    images because we install ntp and ntp conflicts with
		#    systemd-timesyncd.
		#  - Setting variant as minbase and list ntp before
		#    systemd-container in the include list allows debootstrap
		#    to install ntp before systemd, thus satisfying the
		#    package dependencies.
		# Note that we do not run into those problems during live-build
		# because debootstrap is already run with variant=minbase and
		# systemd is not installed by debootstrap, but rather by
		# delphix-platform which pulls both ntp and systemd.
		#
		debootstrap --no-check-gpg --variant=minbase \
			--components=delphix --include=ntp,systemd-container \
			focal "$DIRECTORY" "file://$IMAGE_PATH" 1>&2 ||
			die "failed to debootstrap upgrade filesystem"

		#
		# Now that we've successfully run "deboostrap", we can
		# unmount these datasets that were mounted above.
		#
		unmount_upgrade_container_dataset "rpool/ROOT/$CONTAINER/log"
		unmount_upgrade_container_dataset "rpool/ROOT/$CONTAINER/data"
		unmount_upgrade_container_dataset "rpool/ROOT/$CONTAINER/home"

		if $TMP_DATASETS_EXIST; then
			unmount_upgrade_container_dataset "rpool/ROOT/$CONTAINER/tmp"
			unmount_upgrade_container_dataset "rpool/ROOT/$CONTAINER/vartmp"
		fi
		;;
	esac

	#
	# We rely on the "/etc/fstab" file to mount the non-root ZFS
	# filesystems, so that when a specific rootfs dataset is booted,
	# it'll automatically mount the correct non-rootfs datasets
	# associated with that rootfs dataset. The mounts need to happen
	# before the zfs-import service is run.
	#
	cat <<-EOF >"$DIRECTORY/etc/fstab"
		rpool/ROOT/$CONTAINER/home /home zfs defaults,nodev,x-systemd.before=zfs-import-cache.service 0 0
		rpool/ROOT/$CONTAINER/data /var/delphix zfs defaults,x-systemd.before=zfs-import-cache.service 0 0
		rpool/ROOT/$CONTAINER/log  /var/log     zfs defaults,x-systemd.before=zfs-import-cache.service 0 0
		rpool/crashdump            /var/crash   zfs defaults,x-systemd.before=zfs-import-cache.service,x-systemd.before=kdump-tools.service 0 0
	EOF

	if $TMP_DATASETS_EXIST; then
		cat <<-EOF >>"$DIRECTORY/etc/fstab"
			         rpool/ROOT/$CONTAINER/tmp  /tmp         zfs defaults,nosuid,nodev,exec,x-systemd.before=zfs-import-cache.service 0 0
			         rpool/ROOT/$CONTAINER/vartmp  /var/tmp  zfs defaults,nosuid,nodev,exec,x-systemd.before=zfs-import-cache.service 0 0
		EOF
	fi

	#
	# DLPX-75089 - Since older versions of Delphix did not properly
	# disable the NFS services within the upgrade container, we have
	# to dynamically disable them here. This way, when the container
	# is started, those NFS services will not run (no matter the
	# version of Delphix we're upgrading from).
	#
	# DLPX-78307 - Similarly, we must disable "google-guest-agent".
	# DLPX-94130 - Also, disable the "delphix-osadmin" service.
	# DLPX-94115 - Also, disable "zfs-zed" service.
	#
	for svc in \
		"nfs-mountd" "nfs-server" "rpc-statd" "rpc-statd-notify" \
		"google-guest-agent" "delphix-osadmin" "zfs-zed"; do

		if [[ "$svc" == "zfs-zed" ]]; then
			#
			# The delphix-platform package already delivers the
			# "override.conf" file for "zfs-zed" service. Thus, we
			# need to use a different filename to avoid conflicting
			# with that pre-existing override file.
			#
			filename="upgrade-container.conf"
		else
			filename="override.conf"
		fi

		[[ -e "$DIRECTORY/lib/systemd/system/$svc.service.d/$filename" ]] &&
			continue

		mkdir -p "$DIRECTORY/lib/systemd/system/$svc.service.d" ||
			die "failed to create override directory for '$svc' service"

		cat >"$DIRECTORY/lib/systemd/system/$svc.service.d/$filename" <<-EOF ||
			[Unit]
			ConditionVirtualization=!container
		EOF
			die "failed to create override file for '$svc' service"
	done

	mkdir -p "/etc/systemd/nspawn" ||
		die "failed to create directory: '/etc/systemd/nspawn'"

	#
	# We need to change some of the default configuration options
	# for the container, in order for it to behave as we expected:
	#
	# * PrivateUsers: We want the UIDs in the container to match the
	#   UIDs in the host. This way the container can execute commands
	#   (e.g. zfs) as the normal root user.
	#
	# * PrivateUsersChown: Since we set PrivateUsers to "no", we
	#   need to also ensure systemd-nspawn doesn't attempt to chown
	#   the containers root filesystem. Normally, with PrivateUsers
	#   set to "yes", the container's root filesystem would be
	#   chowned to match the UID mapping used by the container.
	#
	# * Private: We set networking to "private" so that the
	#   container can use ports without conflicting with ports that
	#   are already in used by the host.
	#
	# * VirtualEthernet: Since we're using private networking (see
	#   above), if we enable a virtual NIC, that will automatically
	#   result in IP forwarding being enabled, and LRO being disabled.
	#   We've found that with IP forwarding on and LRO off, network
	#   throughput can become up to 15% slower, adversely affecting
	#   workloads such as replication, DB sync, etc. Thus, we
	#   intentionally disable this setting, to avoid the network
	#   performance impact.
	#
	# * Bind=/dev/zfs: We set this so that zfs/zpool/libzpool/etc.
	#   is usable from within the container.
	#
	# * Bind=/sys/module: Starting with Ubuntu 20.04, /sys is mounted
	#   as tmpfs rather than sysfs and it seems like some sub-drectories
	#   are excluded by default, such as /sys/module. We need that
	#   directory to be present to run some commands (such as zfs).
	#
	cat >"/etc/systemd/nspawn/$CONTAINER.nspawn" <<-EOF ||
		[Exec]
		PrivateUsers=no
		[Network]
		Private=yes
		VirtualEthernet=no
		[Files]
		PrivateUsersChown=no
		Bind=/dev/zfs
		Bind=/sys/module
	EOF
		die "failed to create container configuration file"

	#
	# Certain software (e.g. update-grub) running in the container
	# require access to the disk backing the root filesystem. Thus,
	# we expose this device to the container here; we're careful to
	# only expose it read-only, though, to prevent software in the
	# container from inadvertently corrupting the device.
	#
	for device in $(grub-probe --target=device /); do
		cat >>"/etc/systemd/nspawn/$CONTAINER.nspawn" <<-EOF ||
			BindReadOnly=$device
		EOF
			die "failed to add '$device' to container config file"

		pkname=$(lsblk -pn -o pkname "$device" | head -n1)
		if [[ -n "$pkname" ]]; then
			cat >>"/etc/systemd/nspawn/$CONTAINER.nspawn" <<-EOF ||
				BindReadOnly=$pkname
			EOF
				die "failed to add '$pkname' to container config file"
		fi

	done

	#
	# Since UPDATE_DIR is stored on a seperate ZFS filesystem than
	# the root filesysytem, we need to explicitly make this
	# directory available inside of the upgrade container,
	# which is what we're doing here.
	#
	# We need UPDATE_DIR to be available inside of the container so
	# that we can use the APT repository that it contains to upgrade
	# the packages inside the container, and verify that process.
	#
	cat >>"/etc/systemd/nspawn/$CONTAINER.nspawn" <<-EOF ||
		Bind=$UPDATE_DIR
	EOF
		die "failed to add '$UPDATE_DIR' to container config file"

	#
	# We also need to make "/domain0" available from within the
	# container, since that's required by the "upgrade-verify" JAR
	# that's run later. This allows the Virtualization upgrade
	# verification to verify the contents of it's database (e.g. run
	# flyway migration) is compatible with the new version of the
	# Virtualization application.
	#
	if [[ -d "/domain0" ]]; then
		cat >>"/etc/systemd/nspawn/$CONTAINER.nspawn" <<-EOF ||
			Bind=/domain0
		EOF
			die "failed to add '/domain0' to container config file"
	fi

	#
	# Lastly, we create the log directory and bind mount this into
	# the container. This is meant as a way for software running in
	# the container, to share files with software running on the
	# host; e.g. during upgrade verify, this directory can be used
	# to store logs, such that they persist after the container is
	# destroyed.
	#
	mkdir -p "$LOG_DIRECTORY" ||
		die "failed to create directory: '$LOG_DIRECTORY'"
	cat >>"/etc/systemd/nspawn/$CONTAINER.nspawn" <<-EOF ||
		Bind=$LOG_DIRECTORY
	EOF
		die "failed to add '$LOG_DIRECTORY' to container config file"

	#
	# We want to enable all available capabilities to the container
	# that we will use to run the ugprade verification. Ideally, we
	# would accomplish this by using "CAPABILITY=all" in the
	# "nspawn" configuration file generated above, but that's not
	# possible. The "CAPABILITY" field only understands actual
	# capabilities (e.g. CAP_SYS_ADMIN), and fails to parse the
	# special value "all".
	#
	# Thus, to workaround this limitation, we override the command
	# that is executed by systemd when starting the container's
	# service, such that it will pass the "--capability=all" option
	# to "systemd-nspawn".
	#
	mkdir -p "/etc/systemd/system/systemd-nspawn@$CONTAINER.service.d" ||
		die "failed to create container service override directory"
	cat >"/etc/systemd/system/systemd-nspawn@$CONTAINER.service.d/override.conf" <<-EOF ||
		[Service]
		ExecStart=
		ExecStart=/usr/bin/systemd-nspawn --quiet --boot --capability=all --machine=%i
	EOF
		die "failed to create container service override file"

	fix_and_migrate_services "$CONTAINER"

	echo "$CONTAINER"
}

function start() {
	if [[ ! -d "/var/lib/machines/$CONTAINER" ]] ||
		[[ ! -f "/etc/systemd/nspawn/$CONTAINER.nspawn" ]] ||
		[[ ! -d "/etc/systemd/system/systemd-nspawn@$CONTAINER.service.d" ]] ||
		! zfs list "rpool/ROOT/$CONTAINER" &>/dev/null ||
		! zfs list "rpool/ROOT/$CONTAINER/root" &>/dev/null ||
		! zfs list "rpool/ROOT/$CONTAINER/home" &>/dev/null ||
		! zfs list "rpool/ROOT/$CONTAINER/data" &>/dev/null ||
		! zfs list "rpool/ROOT/$CONTAINER/log" &>/dev/null ||
		($TMP_DATASETS_EXIST && {
			! zfs list "rpool/ROOT/$CONTAINER/tmp" &>/dev/null ||
				! zfs list "rpool/ROOT/$CONTAINER/vartmp" &>/dev/null
		}); then
		die "container '$CONTAINER' non-existent or mis-configured"
	fi

	systemctl restart systemd-reexec.service 2>/dev/null
	machinectl start "$CONTAINER" ||
		die "failed to start container '$CONTAINER'"

	#
	# When starting the container above with "machinectl start", the
	# command will return prior to the container having fully
	# completed it's boot process. Thus, to ensure we don't attempt
	# the verification steps prior to the container being ready, we
	# first wait for the container to finish booting.
	#
	# shellcheck disable=SC2034
	for i in {1..600}; do
		if run /bin/systemctl is-active default.target &>/dev/null; then
			break
		fi

		sleep 1
	done

	run /bin/systemctl is-active default.target &>/dev/null ||
		die "'default.target' inactive in container '$CONTAINER'"
}

function stop() {
	systemctl restart systemd-reexec.service 2>/dev/null
	machinectl terminate "$CONTAINER" ||
		die "failed to termiante container: '$CONTAINER'"

	#
	# The above command used to terminate the container is not
	# synchronous, and may return before termination of the
	# container is complete. Thus, we poll here, and wait for the
	# the termination to complete before continuing.
	#
	# shellcheck disable=SC2034
	for i in {1..600}; do
		if ! machinectl status "$CONTAINER" &>/dev/null; then
			break
		fi

		sleep 1
	done

	#
	# Starting the upgrade container would have enabled ip forwarding
	# on the host (and in turn disabled LRO). Reset these settings
	# on a best effor basis.
	#
	sysctl -w net.ipv4.ip_forward=0 || warn "failed to disable ip port forwarding"

	#
	# Find all the interfaces configured on the host and set
	# lro on where possible. The sed command retrieves the names of the
	# interfaces. The name of the virtual interfaces of containers could
	# have an @ symbol followed by device name in the output of the ethtool
	# and this needs to be trimmed off.
	#

	for i in $(ip -br link | sed 's/^\([^ @]\+\).*/\1/'); do
		fixed=$(ethtool -k "$i" | grep large-receive-offload | grep -i fixed)
		if [[ -z "$fixed" ]]; then
			echo "updating lro setting for nic $i"
			ethtool -K "$i" lro on || warn "failed to set lro ON for nic '$i'"
		fi
	done

	machinectl status "$CONTAINER" &>/dev/null &&
		die "timeout waiting for container termination: '$CONTAINER'"

	#
	# We don't want to return the error code from the call to
	# "machinectl status" above, so we explicitly return success if
	# we've reached this far.
	#
	return 0
}

function destroy() {
	rm -f "/etc/systemd/nspawn/$CONTAINER.nspawn" ||
		die "failed to remove file: '$CONTAINER.nspawn'"

	rm -rf "/etc/systemd/system/systemd-nspawn@$CONTAINER.service.d" ||
		die "failed to remove directory: $CONTAINER.service.d"

	if zfs list "rpool/ROOT/$CONTAINER" &>/dev/null; then
		#
		# In order to safely perform the recursive destroy below,
		# we need to ensure the filesystems are unmounted in the
		# correct order. Since the "log", "data", "home", "tmp" and
		# "vartmp" datasets are mounted inside the "root" dataset,
		# we need to unmount these datasets before attempting
		# to unmount (and/or destroy) the "root" dataset.
		#
		# Further, we don't check the return value of these
		# commands for simplicity's sake. If these fail, it could
		# be because they aren't mounted, or due to an actual
		# failure to unmount. If those datasets cannot be
		# unmounted, this will cause the destroy to fail below,
		# which we will catch, and then notify the user.
		#
		umount "rpool/ROOT/$CONTAINER/log" &>/dev/null
		umount "rpool/ROOT/$CONTAINER/data" &>/dev/null
		umount "rpool/ROOT/$CONTAINER/home" &>/dev/null
		if $TMP_DATASETS_EXIST; then
			umount "rpool/ROOT/$CONTAINER/tmp" &>/dev/null
			umount "rpool/ROOT/$CONTAINER/vartmp" &>/dev/null
		fi
		umount "rpool/ROOT/$CONTAINER/root" &>/dev/null

		zfs destroy -r "rpool/ROOT/$CONTAINER" ||
			die "failed to destroy container dataset: '$CONTAINER'"
	fi

	ROOTFS_DATASET=$(get_mounted_rootfs_container_dataset)
	[[ -n "$ROOTFS_DATASET" ]] ||
		die "unable to determine mounted rootfs container dataset"

	if zfs list "$ROOTFS_DATASET@container-$CONTAINER" &>/dev/null; then
		zfs destroy -r "$ROOTFS_DATASET@container-$CONTAINER" ||
			die "failed to destroy container snapshot: '$CONTAINER'"
	fi

	if [[ -d "/var/lib/machines/$CONTAINER" ]]; then
		rm -d "/var/lib/machines/$CONTAINER" ||
			die "failed to remove container directory: '$CONTAINER'"
	fi
}

function run() {
	#
	# We've seen cases where systemd-run fails to exit, even after
	# it's run the comamnds/script specified. We've "fixed" this in
	# the past by executing "systemd daemon-reexec", and retrying
	# the upgrade. Thus, to try and avoid the failure to begin with,
	# we restart this service, which serves to run "daemon-reexec".
	#
	# This will fail on versions of Delphix that don't yet have
	# this service, so we hide any failure to account for that.
	#
	systemctl restart systemd-reexec.service 2>/dev/null

	systemd-run \
		--machine="$CONTAINER" \
		--setenv=CONTAINER="$CONTAINER" \
		--quiet --wait --pipe -- "$@"
}

function shell() {
	machinectl shell "$CONTAINER"
}

function convert_to_rootfs() {
	#
	# We're relying on the "mountpoint" property for the "data" and
	# "home" datasets already being set properly when those datasets
	# are first created, so we don't explicitly set them here.
	#
	# Additionally, we're also relying on the "canmount" property of
	# the "root" dataset already being set properly, so we don't
	# explicitly set that here, either.
	#
	zfs umount "rpool/ROOT/$CONTAINER/root" ||
		die "'zfs umount rpool/ROOT/$CONTAINER/root' failed"
	zfs set mountpoint=/ "rpool/ROOT/$CONTAINER/root" ||
		die "zfs set mountpoint rpool/ROOT/$CONTAINER/root' failed"
}

function get_type() {
	local origin

	origin=$(zfs get -Hpo value origin "rpool/ROOT/${CONTAINER}/root")
	[[ -n "${origin}" ]] ||
		die "failed to get origin for container '${CONTAINER}'"

	case "${origin}" in
	-)
		echo "not-in-place"
		;;
	*)
		echo "in-place"
		;;
	esac
}

function do_upgrade_container() {
	local type
	type=$(get_type)
	case $type in
	in-place | not-in-place)
		run "$IMAGE_PATH/execute" ||
			die "'$IMAGE_PATH/execute' failed in '$CONTAINER'"
		;;
	*)
		die "unsupported upgrade container type specified: '$type'"
		;;
	esac

	#
	# Before we return, we ensure all of that changes made to the
	# root pool, as part of upgrading the container, are on disk.
	#
	zpool sync rpool || die "'zpool sync rpool' failed"
}

function usage() {
	echo "$(basename "$0"): $*" >&2

	PREFIX_STRING="Usage: $(basename "$0")"
	PREFIX_NCHARS=$(echo -n "$PREFIX_STRING" | wc -c)
	PREFIX_SPACES=$(printf "%.s " $(seq "$PREFIX_NCHARS"))

	echo "$PREFIX_STRING create [in-place|not-in-place|rollback]"
	echo "$PREFIX_SPACES start <container>"
	echo "$PREFIX_SPACES stop <container>"
	echo "$PREFIX_SPACES destroy <container>"
	echo "$PREFIX_SPACES run <container> <command>"
	echo "$PREFIX_SPACES shell <container>"
	echo "$PREFIX_SPACES upgrade <container>"
	echo "$PREFIX_SPACES convert-to-rootfs <container>"
	echo "$PREFIX_SPACES get-type <container>"

	exit 2
}

[[ "$EUID" -ne 0 ]] && die "must be run as root"

case "$1" in
create)
	[[ $# -lt 2 ]] && usage "too few arguments specified"
	[[ $# -gt 2 ]] && usage "too many arguments specified"

	case "$2" in
	in-place | not-in-place | rollback)
		create_upgrade_container "$2"
		;;
	*)
		usage "invalid create type specified: '$2'"
		;;
	esac

	;;
start)
	[[ $# -lt 2 ]] && usage "too few arguments specified"
	[[ $# -gt 2 ]] && usage "too many arguments specified"
	CONTAINER="$2"
	start
	;;
stop)
	[[ $# -lt 2 ]] && usage "too few arguments specified"
	[[ $# -gt 2 ]] && usage "too many arguments specified"
	CONTAINER="$2"
	stop
	;;
destroy)
	[[ $# -lt 2 ]] && usage "too few arguments specified"
	[[ $# -gt 2 ]] && usage "too many arguments specified"
	CONTAINER="$2"
	destroy
	;;
run)
	[[ $# -lt 3 ]] && usage "too few arguments specified"
	CONTAINER="$2"
	shift 2
	run "$@"
	;;
shell)
	[[ $# -lt 2 ]] && usage "too few arguments specified"
	CONTAINER="$2"
	shift 2
	shell
	;;
upgrade)
	[[ $# -lt 2 ]] && usage "too few arguments specified"
	[[ $# -gt 2 ]] && usage "too many arguments specified"
	CONTAINER="$2"
	do_upgrade_container
	;;
convert-to-rootfs)
	[[ $# -lt 2 ]] && usage "too few arguments specified"
	[[ $# -gt 2 ]] && usage "too many arguments specified"
	CONTAINER="$2"
	convert_to_rootfs
	;;
get-type)
	[[ $# -lt 2 ]] && usage "too few arguments specified"
	[[ $# -gt 2 ]] && usage "too many arguments specified"
	CONTAINER="$2"
	get_type
	;;
*)
	usage "invalid option specified: '$1'"
	;;
esac
