#
# Copyright 2019 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
- apt:
    name:
      - adoptopenjdk-java8-jdk
      - ant
      - bash
      - build-essential
      - docker.io
      - git
      - python3-minimal
    state: present

#
# The UI-precommit suite requires some chromium-browser dependendencies to be
# installed. However on 20.04 chromium is provided by a snap, and the
# "chromium-browser" package neither provides any dependencies nor the actual
# chromium browser, but rather directs users to install the chromium snap.
# While we could get chromium from a thrid party PPA, we do not actually need
# chromium for UI-precommit to work, but only some of the libraries that
# came as dependencies. As such we install here all the lib dependencies
# that were brought in by the chromium-browser package on 18.04 as per:
# https://packages.ubuntu.com/bionic/chromium-browser.
#
- apt:
    name:
      - libasound2
      - libatk-bridge2.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libc6
      - libcairo2
      - libcups2
      - libdbus-1-3
      - libdrm2
      - libexpat1
      - libgbm1
      - libgcc1
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libgtk-3-0
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libwayland-client0
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxi6
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - libxshmfence1
      - libxss1
      - libxtst6
    state: present

- user:
    name: testrunner
    comment: "Delphix"
    home: /export/home/testrunner
    groups: docker
    password:
      "$6$pWQE0MPZWgue7fNC$8RvR0u04Mt67792b.x4ao0G2Z/H/hrYPWezOqCkz59MIA\
       RcFa0NU7XOtATAgo5Nj26kGjKVcj4D8tvo.E/kuc1"
    shell: /bin/bash

- authorized_key:
    user: testrunner
    state: present
    key:
      "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAyvw2gQRkDqrRY5qxUn0VYAL6Rtt1/\
       NJhftc/KGt/66yinscWISJLzaumXW+GZ9KPgPb15hl0tWAdQxqeF6lmHVo5Ugj6e/\
       mJzDxN+1E39Ejj+lZbm1LCSjjp3Ly+fTkkmrUT1q9mSMbq8Pc1huCmX8MsFLwF7zh\
       56OlxQuTDjRqh8GMoy32JyKgddPjrL/YOhnfhxYirFHR+uXukRrtZbwI598d1gREe\
       kKkPncA5N/O6e/jD+JXxDYi2BPIIDZLb1yzFlHb8xMjXEkMPdfngv1Cs0ib//0qwG\
       etvKgydCTO7Au7b5Na3ArVlaokV96hVn8GpMt8SFpEbc6Fw3ul5uw=="
